/**
 * Publish demo sites generated by the old lead-tracking app, which kept them on
 * disk as generated-sites/<slug>/index.html and linked leads to
 * /demos/<slug>/index.html.
 *
 *   npm run demos:import -- --from ../../leads/lead-tracking/generated-sites
 *   npm run demos:import -- --from <dir> --dry-run
 *
 * Each page gets a demo.bezikee.com/<uuid> link, and a lead still pointing at
 * the old /demos/ path is repointed at it. Safe to re-run: a business keeps its
 * id and only its HTML is refreshed, and a demo link someone typed in by hand is
 * never overwritten.
 *
 * Run it after the database has been copied across, so the business ids in the
 * directory names match rows that exist.
 */
import "./load-env.mjs";

import { randomUUID } from "node:crypto";
import fs from "node:fs";
import path from "node:path";

import { eq, sql } from "drizzle-orm";
import { drizzle } from "drizzle-orm/postgres-js";
import postgres from "postgres";

import { businesses, demoSites, leadEvents, leads } from "@admin/lib/db/schema";
import { demoUrl } from "@admin/lib/demo/url";

const argv = process.argv.slice(2);
const fromAt = argv.indexOf("--from");
const from = fromAt >= 0 ? argv[fromAt + 1] : undefined;
const dryRun = argv.includes("--dry-run");

if (!from) {
  console.error("Usage: npm run demos:import -- --from <generated-sites dir> [--dry-run]");
  process.exit(1);
}

const DATABASE_URL = process.env.DATABASE_URL;
if (!DATABASE_URL) throw new Error("DATABASE_URL is not set");

/** Is this connection string for a database on this machine? */
function isLocal(url: string): boolean {
  try {
    return ["localhost", "127.0.0.1", "[::1]"].includes(new URL(url).hostname);
  } catch {
    return false;
  }
}

const root = path.resolve(from);
if (!fs.existsSync(root)) throw new Error(`${root} does not exist`);

const client = postgres(DATABASE_URL, {
  max: 1,
  onnotice: () => {},
  ssl: isLocal(DATABASE_URL) ? false : "require",
});
const db = drizzle(client);

let published = 0;
let skipped = 0;

try {
  for (const slug of fs.readdirSync(root).sort()) {
    const page = path.join(root, slug, "index.html");
    if (!fs.existsSync(page)) continue;

    // siteSlug() always ended in the business id: peluqueria-sin-web-823.
    const businessId = Number(/-(\d+)$/.exec(slug)?.[1]);
    if (!Number.isInteger(businessId)) {
      console.warn(`skip  ${slug}: no business id at the end of the name`);
      skipped++;
      continue;
    }

    const [business] = await db
      .select({ id: businesses.id, name: businesses.name })
      .from(businesses)
      .where(eq(businesses.id, businessId))
      .limit(1);

    if (!business) {
      console.warn(`skip  ${slug}: business ${businessId} is not in this database`);
      skipped++;
      continue;
    }

    const html = fs.readFileSync(page, "utf8");

    if (dryRun) {
      console.log(`would publish  ${slug}  →  ${business.name}`);
      published++;
      continue;
    }

    const [row] = await db
      .insert(demoSites)
      .values({ id: randomUUID(), businessId, html })
      .onConflictDoUpdate({
        target: demoSites.businessId,
        set: { html, updatedAt: sql`now()` },
      })
      .returning({ id: demoSites.id });

    const link = demoUrl(row.id);

    // Only repoint links that still name the old path. Anything else was set by
    // hand and is somebody's decision.
    const repointed = await db
      .update(leads)
      .set({ demoUrl: link, updatedAt: new Date() })
      .where(
        sql`${leads.businessId} = ${businessId} and (${leads.demoUrl} is null or ${leads.demoUrl} like '/demos/%')`,
      )
      .returning({ id: leads.id });

    for (const lead of repointed) {
      await db.insert(leadEvents).values({
        leadId: lead.id,
        type: "note",
        message: `Demo site moved to ${link}.`,
      });
    }

    console.log(`published  ${slug}  →  ${link}${repointed.length ? "  (lead updated)" : ""}`);
    published++;
  }
} finally {
  await client.end();
}

console.log(
  `\n${dryRun ? "Would publish" : "Published"} ${published}, skipped ${skipped}.`,
);
